@url = http://localhost:9999
@json = Content-Type: application/json

###send verification code
post {{url}}/api/auth
{{json}}

{
    "email" : "runzw0817@gmail.com"
}

###register
post {{url}}/api/register
{{json}}

{
    "name" : "runzw",
    "password" : "runzw",
    "email" : "runzw0817@gmail.com",
    "code" : "696012"
}

###login
post {{url}}/api/login
{{json}}

{
    "email" : "runzw0817@gmail.com",
    "password" : "runzw"
}

###header
get {{url}}/api/cur_user/d6f9bc06-ca4c-42c3-b6c1-ba1f66ab383c

###header
get {{url}}/api/cur_user/

###Get user infomation
get {{url}}/api/cur_user/info

###logout
get {{url}}/api/logout

