@url = http://localhost:9999
@json = Content-Type: application/json

###register
post {{url}}/api/register
{{json}}

{
    "username" : "runzw",
    "password" : "runzw"
}

###login
post {{url}}/api/login
{{json}}

{
    "username" : "runzw",
    "password" : "runzw"
}

###login
get {{url}}/api/logout

###cookie-session
get {{url}}/api/cookie-session

###header
get {{url}}/api/userStatus/runzw
###header
get {{url}}/api/userStatus/_none_